
import type { Product } from "@/lib/types"

export const products: Product[] = [
  {
  id: "1",
  name: 'BirdsNature Birds Vitamin & Calcium Supplement Combo Pack 30ml Each',
  slug: 'birdsnature-vitamin-calcium-combo',
  description: 'A combo pack of 30ml each Vitamin and Calcium supplements specially formulated for birds. Supports bone strength, immunity, and overall health.',
  price: 229,
  image: "https://m.media-amazon.com/images/I/61+T9zsjECL.SX522.jpg",
  image1: "https://m.media-amazon.com/images/I/61xBSlX9bvL.SL1500.jpg",
  image2: "https://m.media-amazon.com/images/I/61cvTZcZIDL.SL1500.jpg",
  image3: "https://m.media-amazon.com/images/I/61zNw0ulD4L.SL1500.jpg",
  video:"https://res.cloudinary.com/dcdptwusy/video/upload/v1750697318/id1_yaa7bq.mp4",
  poster:"https://png.pngtree.com/png-clipart/20230821/original/pngtree-vector-illustration-of-flat-logo-app-with-play-button-icon-vector-png-image_10573229.png",
  category: "supplements",
  pet: "bird",
  rating: 4.4,
  reviewCount: 76,
  featured: false,
  stock: 40,
  tags: ['bird supplement', 'vitamin', 'calcium', 'health care']

  },
  {
    id: "2",
    name: "Vetenex - Koff Out Bird",
    slug: "vetenex-koff-out-bird",
    description: "Respiratory support syrup for birds to treat cough and cold symptoms.",
    price: 175.0,
    image: "https://5.imimg.com/data5/SELLER/Default/2023/5/305964303/FF/WD/MC/21713598/respiratory-syrup-cough-cold-medicine-for-birds-100-ml-500x500.jpg",
    image1:"https://m.media-amazon.com/images/I/616ZUcjDTAL.SL1500.jpg",
    image2:"https://m.media-amazon.com/images/I/71yef8W32oL.SL1500.jpg",
    image3:"https://m.media-amazon.com/images/I/71v-LPFU8sL.SL1500.jpg",
    video:"https://res.cloudinary.com/dcdptwusy/video/upload/v1750697338/id2_du7pzl.mp4",
    category: "supplements",
    pet: "bird",
    rating: 4.1,
    reviewCount: 87,
    featured: false,
    stock: 18,
    tags: ["supplements", "cold", "syrup"]
  },
  {
    id: "3",
    name: "Vetenex Catch Worm Bird - Dewormer",
    slug: "vetenex-catch-worm-bird",
    description: "Liquid herbal dewormer for birds to remove internal parasites.",
    price: 145.0,
    image: "https://m.media-amazon.com/images/I/715dHXDZUlL.jpg",
    image1:"https://vetenex.com/wp-content/uploads/2024/08/2_Page-30.jpg",
    image2:"https://vetenex.com/wp-content/uploads/2024/08/3_Page-41.jpg",
    image3:"https://vetenex.com/wp-content/uploads/2024/08/5_Page-32.jpg",
    video:"https://res.cloudinary.com/dcdptwusy/video/upload/v1750697949/id3_boqiey.mp4",
    category: "supplements",
    pet: "bird",
    rating: 4.5,
    reviewCount: 73,
    featured: false,
    stock: 30,
    tags: ["dewormer", "herbal", "health"]
  },
  {
    id: "4",
    name: "Kaytee's Nutrisoft Conure and Parrot Food",
    slug: "kaytee-nutrisoft-parrot-food",
    description: "Balanced and nutritious food specially formulated for parrots.",
    price: 420.0,
    image: "https://m.media-amazon.com/images/I/81DNZ7ac2nL.jpg",
    image1:"https://www.kaytee.com/-/media/Project/OneWeb/Kaytee/US/nutrisoft/products/parrot-conure/PB_NutriSoft_Enhanced_Product_Hero_ParCon.jpg",
    image2:"https://www.kaytee.com/-/media/Project/OneWeb/Kaytee/US/nutrisoft/vet-recommended.png",
    image3:"https://www.kaytee.com/-/media/Project/OneWeb/Kaytee/US/nutrisoft/products/parrot-conure/PB_NutriSoft_Enhanced_PickyEaters_Parrot.jpg",
    video:"https://res.cloudinary.com/dcdptwusy/video/upload/v1750698063/id4_fqrg3y.mp4",
    category: "food",
    pet: "bird",
    rating: 4.6,
    reviewCount: 102,
    featured: true,
    stock: 22,
    tags: ["food", "parrot", "nutritious"]
  },
  {
    id: "5",
    name: "Clown Fish - Cat's Chew Toy",
    slug: "clown-fish-cat-chew-toy",
    description: "A playful clown fish toy that encourages chewing and keeps cats entertained.",
    price: 139.0,
    image: "https://m.media-amazon.com/images/I/71k1AUdlESL.SL1500.jpg",
    image1:"https://m.media-amazon.com/images/I/71Wk7IhjeJL.SL1500.jpg",
    image2:"https://m.media-amazon.com/images/I/71204O6gDrL.SL1500.jpg",
    image3:"https://m.media-amazon.com/images/I/71Lls-hhC3L.SL1500.jpg",
    video:"https://res.cloudinary.com/dcdptwusy/video/upload/v1750698069/id5_o37flr.mp4",
    category: "toys",
    pet: "cat",
    rating: 4.4,
    reviewCount: 67,
    featured: true,
    stock: 40,
    tags: ["toy", "chew", "fish"]
  },
  {
    id: "6",
    name: "Benevo Vegan Duo Cat and Dog Food",
    slug: "benevo-vegan-cat-dog-food",
    description: "A vegan-friendly dry food for cats and dogs with essential nutrients.",
    price: 549.0,
    image: "https://myaistra.com/wp-content/uploads/2017/12/erasebg-transformed-e1739170052106.png",
    image1:"https://m.media-amazon.com/images/I/91Xz1UNDvFL.SL1500.jpg",
    image2:"https://m.media-amazon.com/images/I/91N-RqjOA6L.SL1500.jpg",
    image3:"https://m.media-amazon.com/images/I/81ajfcqwLBL.SL1500.jpg",
    video:"https://res.cloudinary.com/dcdptwusy/video/upload/v1750698083/id6_iqcquh.mp4",
    category: "food",
    pet: "cat",
    rating: 4.0,
    reviewCount: 95,
    featured: false,
    stock: 34,
    tags: ["vegan", "dry food", "nutritious"]
  },
  {
    id: "7",
    name: "Whiskas Dry Food with Tuna for Adult Cats",
    slug: "whiskas-dry-food-tuna",
    description: "Crunchy and delicious tuna-flavored dry food for adult cats.",
    price: 699.0,
    image: "https://media.diy.com/is/image/KingfisherDigital/7kg-whiskas-1-adult-complete-dry-cat-food-with-tuna-bulk-pack-cat-biscuits~5900951299209_01c_MP?$MOB_PREV$&$width=600&$height=600",
    image1:"https://m.media-amazon.com/images/I/61Jkp+u5R8L.SL1000.jpg",
    image2:"https://m.media-amazon.com/images/I/61i2pHaklHL.jpg",
    image3:"https://m.media-amazon.com/images/I/71iUGkmet8L.SL1500.jpg",
    video:"https://res.cloudinary.com/dcdptwusy/video/upload/v1750697816/id7_itcrkl.mp4",
    category: "food",
    pet: "cat",
    rating: 4.3,
    reviewCount: 160,
    featured: true,
    stock: 50,
    tags: ["dry food", "tuna", "adult"]
  },
  {
    id: "8",
    name: "Whiskas Wet Food for Adult Cats",
    slug: "whiskas-wet-food-adult-cats",
    description: "Delicious and moist food for adult cats packed with nutrients.",
    price: 99.0,
    image: "https://petvetcare.in/cdn/shop/files/WTJ1_900x.webp?v=1731592431",
    image1:"https://m.media-amazon.com/images/I/71AIxKmvzdL.SL1500.jpg",
    image2:"https://m.media-amazon.com/images/I/71QhDUMwIeL.SL1500.jpg",
    image3:"https://m.media-amazon.com/images/I/718yLsyOqHL.SL1500.jpg",
    category: "food",
    pet: "cat",
    rating: 4.2,
    reviewCount: 132,
    featured: false,
    stock: 60,
    tags: ["wet food", "moist", "adult"]
  },
  {
    id: "9",
    name: "Purepet Adult Cat Food",
    slug: "purepet-adult-cat-food",
    description: "Affordable and nutritious dry food for adult cats.",
    price: 370.0,
    image: "https://supertails.com/cdn/shop/files/2_69af71bd-8ea6-43e1-afc8-b35c6fc2dc051_1800x1800.png?v=1739368776",
    image1:"https://m.media-amazon.com/images/I/71CsGF735uL.SL1500.jpg",
    image2:"https://m.media-amazon.com/images/I/61KLQ0NBJTL.SL1500.jpg",
    image3:"https://m.media-amazon.com/images/I/71Gr-jbsimL.SL1500.jpg",
    category: "food",
    pet: "cat",
    rating: 4.1,
    reviewCount: 110,
    featured: false,
    stock: 25,
    tags: ["dry food", "affordable", "adult"]
  },
  {
    id: "10",
    name: "Purepet Kitten Dry Food",
    slug: "purepet-kitten-dry-food",
    description: "Specially designed dry food to support healthy growth of kittens.",
    price: 385.0,
    image: "https://www.pawsandpaws.com/assets/images/ProductImages/3179-1989-purepet-ocean-fish-kitten-dry-food-12kg.png",
    image1:"https://m.media-amazon.com/images/I/814SCV26B8L.SL1500.jpg",
    image2:"https://m.media-amazon.com/images/I/51x-5onXdcL.jpg",
    image3:"https://m.media-amazon.com/images/I/711A+zPuHaL.SL1500.jpg",
    category: "food",
    pet: "cat",
    rating: 4.5,
    reviewCount: 98,
    featured: false,
    stock: 30,
    tags: ["kitten", "dry food", "growth"]
  },
  {
    id: "11",
    name: "Meow Mix Cat Tasty Food",
    slug: "meow-mix-cat-food",
    description: "Tasty and balanced cat food for a happy and healthy life.",
    price: 295.0,
    image: "https://assets.shop.loblaws.ca/products/21383314/b2/en/front/21383314_front_a06_@2.png",
    image1:"https://m.media-amazon.com/images/I/81xBzqiN1CL.SL1500.jpg",
    image2:"https://m.media-amazon.com/images/I/91yD-7WTh1L.SL1500.jpg",
    image3:"https://m.media-amazon.com/images/I/81d2q465l9L.SL1500.jpg",
    category: "food",
    pet: "cat",
    rating: 4.4,
    reviewCount: 108,
    featured: true,
    stock: 42,
    tags: ["meow mix", "balanced", "delicious"]
  },
  {
    id: "12",
    name: "Petvit Calcium Tablets",
    slug: "petvit-calcium-tablets-cat",
    description: "Calcium tablets to support strong bones and teeth for cats.",
    price: 259.0,
    image: "https://m.media-amazon.com/images/I/512ORZoHFtL.SX522.jpg",
    image1:"https://m.media-amazon.com/images/I/51DJqFTvQmL.SL1500.jpg",
    image2:"https://m.media-amazon.com/images/I/71YZQysY+NL.SL1500.jpg",
    image3:"https://m.media-amazon.com/images/I/71oobPaC4KL.SL1500.jpg",
    category: "supplements",
    pet:  "cat",
    rating: 4.6,
    reviewCount: 142,
    featured: true,
    stock: 38,
    tags: ["calcium", "tablet", "bones"]
  },
  {
    
  id: "13",
  name: 'Gratone Amino Pet Syrup',
  slug: 'gratone-amino-pet-syrup',
  description: 'Enriched with Vitamin A, D3 & E, this chicken-flavored syrup supports muscle growth and overall pet health. Ideal for regular supplementation.',
  price: 299,
  image: "https://m.media-amazon.com/images/I/71LkxRmUdrL.SL1500.jpg",
  image1: "https://m.media-amazon.com/images/I/81UJIzVHBVL.SL1500.jpg",
  image2: "https://m.media-amazon.com/images/I/71jh8wjklWL.SL1500.jpg",
  image3: "https://m.media-amazon.com/images/I/81M3XvYyA3L.SL1500.jpg",
  category: "supplements",
  pet: "dog",
  rating: 4.6,
  reviewCount: 134,
  featured: false,
  stock: 25,
  tags: ['vitamin supplement', 'syrup', 'muscle growth', 'chicken flavor']


  },
  {
    id: "14",
    name: "PetRoyale Dog Multivitamin Tablet",
    slug: "petroyale-dog-multivitamin",
    description: "Multivitamin tablets to support the overall health of dogs.",
    price: 399.0,
    image: "https://rukminim2.flixcart.com/image/850/1000/xif0q/shopsy-pet-health-supplement/p/l/1/60-dog-multivitamin-tablet-pet-health-supplement-dog-bone-original-imah9hkuqp2xp99z.jpeg?q=90&crop=false",
    image1:"https://m.media-amazon.com/images/I/61ccXtVQ3SL.SL1000.jpg",
    image2:"https://m.media-amazon.com/images/I/616TwX5TerL.SL1000.jpg",
    image3:"https://m.media-amazon.com/images/I/61H6QqF7wcL.SL1000.jpg",
    category: "supplements",
    pet: "dog",
    rating: 4.5,
    reviewCount: 87,
    featured: false,
    stock: 26,
    tags: ["multivitamin", "health", "tablet"],
    isNew: true
  },
  {
    
  id: "15",
  name: "Bird Parrot Toys Ladders Swing",
  slug: "bird-parrot-toys-ladders-swing",
  description: "Colorful hanging swing with ladders, perfect for parrots and small birds to play, climb, and exercise.",
  price: 349.00,
  image: "https://d3dxkzk9npnkec.cloudfront.net/uploads/images/202403/img_x500_65ebbcbe99c6f6-00495158-51495907.webp",
  image1:"https://d3dxkzk9npnkec.cloudfront.net/uploads/images/202403/img_x500_65ebbcbc540732-04988401-33952753.webp",
  image2:"https://d3dxkzk9npnkec.cloudfront.net/uploads/images/202403/img_x500_65ebbcb32b10d5-06839153-99768657.webp",
  image3:"https://d3dxkzk9npnkec.cloudfront.net/uploads/images/202403/img_x500_65ebbcb6d0c800-81288912-28073848.webp",
  video:"https://res.cloudinary.com/dcdptwusy/video/upload/v1750698371/id15_tgcdof.mp4",
  category: "toys",
  pet: "bird",
  rating: 4.6,
  reviewCount: 89,
  featured: false,
  stock: 52,
  tags: ["swing", "ladder", "bird toy", "parrot toy"],
  isNew: true

  },
  {
    
  id: "16",
  name: "CVALIN Chew Dog Toy",
  slug: "cvalin-chew-dog-toy",
  description: "Durable chew toy designed for aggressive chewers. Helps clean teeth and reduce boredom in dogs.",
  price: 499.00,
  image: "https://m.media-amazon.com/images/I/71+sWvKgy1L.AC_SX679.jpg",
  image1:"https://m.media-amazon.com/images/I/71gfuBTiVDL.AC_SL1500.jpg",
  image2:"https://m.media-amazon.com/images/I/81nBTiS-98L.AC_SL1500.jpg",
  image3:"https://m.media-amazon.com/images/I/71bel3ECunL.AC_SL1500.jpg",
  video:"https://res.cloudinary.com/dcdptwusy/video/upload/v1750697833/id16_kjsgqt.mp4",
  category: "toys",
  pet: "dog",
  rating: 4.4,
  reviewCount: 127,
  featured: false,
  stock: 38,
  tags: ["chew toy", "durable", "dental care"],
  isNew: true


  },
  {
    id: "17",
    name: "Halo Holistic Cage-free Turkey and Sweet Potato Recipe",
    slug: "halo-holistic-turkey-sweet-potato-dog-food",
    description: "Dry dog food made with cage-free turkey and wholesome sweet potatoes for holistic nutrition.",
    price: 2599.00,
    image: "https://assets.petco.com/petco/image/upload/f_auto,q_auto/3714826-center-1",
    image1:"https://m.media-amazon.com/images/I/61al2Wjk1GL.AC_SL1500.jpg",
    image2:"https://m.media-amazon.com/images/I/81lEJcD--TL.AC_SL1500.jpg",
    image3:"https://m.media-amazon.com/images/I/71d0MSoE7ZL.AC_SL1500.jpg",
    category: "food",
    pet: "dog",
    rating: 4.6,
    reviewCount: 188,
    featured: true,
    stock: 30,
    tags: ["dry food", "natural", "holistic", "grain-free"],
    isNew: true

  },
  {
    id: "18",
    name: "Pedigree Tasty Veggies",
    slug: "pedigree-tasty-veggies",
    description: "Delicious and healthy veggie-based dog food.",
    price: 299.0,
    image: "https://m.media-amazon.com/images/I/818bJp70JAL.AC_UF1000,1000_QL80.jpg",
    image1:"https://m.media-amazon.com/images/I/81rDIXpjwVL.SX522.jpg",
    image2:"https://m.media-amazon.com/images/I/71Nq8VuvkCL.SL1500.jpg",
    image3:"https://m.media-amazon.com/images/I/71TicLjg20L.SL1500.jpg",
    category: "food",
    pet: "dog",
    rating: 4.3,
    reviewCount: 143,
    featured: false,
    stock: 38,
    tags: ["veg", "dry food", "tasty"],
    isNew:true
  },
  {
    id: "19",
    name: "Pedigree Puppy Chicken & Rice Wet Food",
    slug: "pedigree-puppy-wet-food",
    description: "Wet food with chicken and rice for puppies’ balanced growth.",
    price: 95.0,
    image: "https://m.media-amazon.com/images/I/51Hw6o+LDAL.SL1001.jpg",
    image1:"https://m.media-amazon.com/images/I/61MNsyW+apL.SL1000.jpg",
    image2:"https://m.media-amazon.com/images/I/61H2o4jnGOL.SL1000.jpg",
   image3:"https://m.media-amazon.com/images/I/61ZG7HSjD6L.SL1000.jpg",
   //video:"https://www.youtube.com/embed/JH0B8H8rhmM" ,
   poster:"https://png.pngtree.com/png-clipart/20230821/original/pngtree-vector-illustration-of-flat-logo-app-with-play-button-icon-vector-png-image_10573229.png",
   video:"https://res.cloudinary.com/dcdptwusy/video/upload/v1750696317/pedigree_chicken_u7qiu2.mp4",
    category: "food",
    pet: "dog",
    rating: 4.5,
    reviewCount: 99,
    featured: true,
    stock: 50,
    tags: ["puppy", "wet food", "chicken"]
   
  },
  {
    id: "20",
    name: "Bio-Groom Tear-Free Shampoo for Puppies",
    slug: "bio-groom-tear-free-shampoo",
    description: "Gentle and tear-free shampoo for puppies with sensitive skin.",
    price: 345.0,
    image: "https://www.pets-lifestyle.com/cdn/shop/files/Bio-GroomFluffyPuppy_Tear-FreeShampoo.png?crop=center&height=500&v=1715156953&width=600",
    image1:"https://m.media-amazon.com/images/I/813MjxZjmBL.SX522.jpg",
    image2:"https://m.media-amazon.com/images/I/714i7SYiGAL.SL1500.jpg",
    image3:"https://m.media-amazon.com/images/I/71ocEOAFApL.SL1500.jpg",
    video:"https://res.cloudinary.com/dcdptwusy/video/upload/v1750698378/id20_frul8v.mp4",
    category: "grooming supplies",
    pet: "dog",
    rating: 4.6,
    reviewCount: 111,
    featured: false,
    stock: 29,
    tags: ["shampoo", "puppy", "tear-free"]
  },
  {
    id: "21",
    name: "Boltz Anti-Tick & Flea Dog Shampoo 200ml",
    slug: "boltz-anti-tick-flea-dog-shampoo-200ml",
    description: "Natural Extracts of Neem, Tulsi & Lemongrass, Anti-Fungal, Anti-Itching Formula, pH Balanced, Healthy Skin and Shiny Coat, Suitable for All Breed Dogs",
    price: 350.0,
    image: "https://m.media-amazon.com/images/I/41GP+3qAANL.jpg",
    image1:"https://m.media-amazon.com/images/I/61BDhmIB55L.SL1200.jpg",
    image2:"https://m.media-amazon.com/images/I/61XXzTTv77L.SL1500.jpg",
    image3:"https://m.media-amazon.com/images/I/61FWkIVTOrL.SL1200.jpg",
    category: "grooming supplies",
    pet: "dog",
    rating: 4.4,
    reviewCount: 89,
    featured: false,
    stock: 20,
    tags: ["shampoo", "coat care", "hydration"],
    isNew: true
  },
  {
  id: "22",
  name: "3 in 1 Cat Steamy Brush Cleanser",
  slug: "cat-steam-brush-cleanser",
  description: "Silicone steam brush with grooming, massage, and cleansing features. Effectively removes loose fur and dirt, keeping your pet clean and relaxed.",
  price: 499.00,
  image: "https://m.media-amazon.com/images/I/61qqVIMO-2L.SL1500.jpg",
  image1:"https://m.media-amazon.com/images/I/71j1Y8ZAYWL.SL1500.jpg",
  image2:"https://m.media-amazon.com/images/I/71UK6s9LnCL.SL1500.jpg",
  image3:"https://m.media-amazon.com/images/I/61UoISiejpL.SL1500.jpg",
  video:"https://res.cloudinary.com/dcdptwusy/video/upload/v1750698395/id22_y0c1il.mp4",
  category: "grooming supplies",
  pet: "cat",
  rating: 4.4,
  reviewCount: 113,
  featured: true,
  stock: 39,
  tags: ["grooming", "steam brush", "massage", "cleanser", "pet brush"],
  isNew: true
},
{
  id: "23",
  name: "Mooncat Waterless Cat Shampoo + Brush",
  slug: "mooncat-waterless-cat-shampoo-brush",
  description: "Licking-safe no-rinse foam shampoo with built-in brush for cats and kittens. Gentle on sensitive skin, reduces dander, paraben-free, and pH balanced for regular grooming.",
  price: 579.00,
  image: "https://m.media-amazon.com/images/I/61qLc48JMbL.SL1000.jpg",
  image1:"https://m.media-amazon.com/images/I/71bjhgoS6CL.SX522.jpg",
  image2:"https://m.media-amazon.com/images/I/61qbUAHAyHL.SL1000.jpg",
  image3:"https://m.media-amazon.com/images/I/61JKekykPTL.SL1000.jpg",
  category: "grooming supplies",
  pet: "cat",
  rating: 4.5,
  reviewCount: 87,
  featured: false,
  stock: 46,
  tags: ["grooming", "waterless shampoo", "dry shampoo", "sensitive skin", "no rinse"]
  
},
{
  id: "24",
  name: "Unitailz Birds Aloe Dry Bath Shampoo",
  slug: "unitailz-birds-aloe-dry-bath-shampoo",
  description: "Instant waterless spray for quick cleaning and refreshing of birds like parrots, pigeons, and sparrows. Enriched with aloe and a fresh fragrance. Easy to use for all bird breeds.",
  price: 299.00,
  image: "https://m.media-amazon.com/images/I/61tkWOQat4L.SL1500.jpg",
  image1:"https://m.media-amazon.com/images/I/61SDEuc-A-L.SX522.jpg",
  image2:"https://m.media-amazon.com/images/I/71WKVbOtRRL.SX522.jpg",
  image3:"https://m.media-amazon.com/images/I/71GxS6mbNWL.SX522.jpg",
  video:"https://res.cloudinary.com/dcdptwusy/video/upload/v1750698409/id24_stq5m1.mp4",
  category: "grooming supplies",
  pet: "bird",
  rating: 4.4,
  reviewCount: 64,
  featured: false,
  stock: 52,
  tags: ["dry shampoo", "grooming", "aloe", "waterless spray", "bird hygiene"],
  isNew: true
},
{
  id: "25",
  name: "MANON ROSA Bird Nail & Beak Grinder",
  slug: "manon-rosa-bird-nail-beak-grinder",
  description: "Safe and quiet grooming tool for birds. Ideal for trimming nails and maintaining beaks of parrots, conures, cockatiels, finches, and parakeets. Comes as a complete grooming kit.",
  price: 799.00,
  image: "https://m.media-amazon.com/images/I/41Lg92qSyEL.jpg",
  image1:"https://images-cdn.ubuy.co.in/677e0e8672cc48404e7ba860-manon-rosa-bird-nail-grinder-bird-beak.jpg",
  image2:"https://images-cdn.ubuy.co.in/677e0e8672cc48404e7ba861-manon-rosa-bird-nail-grinder-bird-beak.jpg",
  image3:"https://images-cdn.ubuy.co.in/677e0e8672cc48404e7ba863-manon-rosa-bird-nail-grinder-bird-beak.jpg",
  video:"https://res.cloudinary.com/dcdptwusy/video/upload/v1750698436/id25_mjnjxu.mp4",
  category: "grooming supplies",
  pet: "bird",
  rating: 4.6,
  reviewCount: 39,
  featured: false,
  stock: 34,
  tags: ["nail grinder", "beak care", "grooming kit", "quiet motor", "safe grooming"],
  isNew: true
},
{
  id: "26",
  name: "The AutoStory Automatic Aquarium Fish Feeder",
  slug: "autostory-automatic-aquarium-fish-feeder",
  description: "Automatic aquarium fish feeder with manual and auto modes, adjustable portion dispenser, two mounting options, and a 0.05 gal food container—perfect for hassle‑free feeding during vacations.",
  price: 1299,
  originalPrice: 3000,
  image: "https://m.media-amazon.com/images/I/61bin+qBcEL.SL1392.jpg",
  image1: "https://m.media-amazon.com/images/I/61wT6-lXoZL.SL1411.jpg",
  image2: "https://m.media-amazon.com/images/I/71qrXyg+ZQL.SL1500.jpg",
  image3: "https://m.media-amazon.com/images/I/610+qO4+heL.SL1500.jpg",
  video:"https://res.cloudinary.com/dcdptwusy/video/upload/v1750698423/id26_crgm7b.mp4",
  category: "grooming supplies",
  pet: "aquaticpets",
  rating: 4.5,
  reviewCount: 58,
  featured: true,
  stock: 25,
  tags: ["aquarium", "feeder", "automatic feeding", "vacation"]
},
{
  id: "27",
  name: "HK Pramukh Automatic Fish Tank Cleaner Liquid | Cloudy Water Remover",
  slug: "hk-pramukh-fish-tank-cleaner",
  description: "Liquid aquarium water clarifier and algae remover. Keeps your tank crystal clear, balances water chemistry, and simplifies maintenance for both fresh and saltwater setups.",
  price: 330,
  image: "https://m.media-amazon.com/images/I/61f4N5hiVGL.SL1500.jpg",
  image1: "https://m.media-amazon.com/images/I/71msYgEewbL.SL1500.jpg",
  image2: "https://m.media-amazon.com/images/I/71I1Tv26x-L.SL1500.jpg",
  image3: "https://m.media-amazon.com/images/I/71wcD21THLL.SL1500.jpg",
  category: "grooming supplies",
  pet: "aquaticpets",
  rating: 3.4,
  reviewCount: 22,
  featured: false,
  stock: 50,
  tags: ["fish tank cleaner", "water clarifier", "algae remover", "aquarium maintenance"]
},
{
  id: "28",
  name: "New Optimum Fish Food",
  slug: "optimum-2025-mini-pellet-fish-food",
  description: "Highly digestible mini pellets enriched with fish meal, corn protein, and fish oil. Designed for aquarium fish growth, color enhancement, and clean water support.",
  price: 380,
  image: "https://m.media-amazon.com/images/I/51RAPV0Yq9L.jpg",
  image1: "https://m.media-amazon.com/images/I/51+1VbacBYL.jpg",
  image2: "https://m.media-amazon.com/images/I/61VQMqi-dqL.jpg",
  image3: "https://m.media-amazon.com/images/I/51Q3EI1r5PL.jpg",
  category: "food",
  pet: "aquaticpets",
  rating: 4.4,
  reviewCount: 62,
  featured: true,
  stock: 100,
  tags: ["fish food", "mini pellet", "nutrition", "aquarium"]
},
{
  id: "29",
  name: "JSquare True Color Red Parrot Fish Food",
  slug: "jsquare-true-color-red-parrot-700g",
  description: "High‑protein (40%) granules enriched with Omega-3, vitamins, and astaxanthin to enhance natural color, boost growth, and reduce stomach bloating – perfect for Red Parrot fish.",
  price: 819,
  originalPrice:1000,
  image: "https://m.media-amazon.com/images/I/71ftlyvyoML.SL1500.jpg",
  image1: "https://m.media-amazon.com/images/I/61fwsMROlWL.SL1500.jpg",
  image2: "https://m.media-amazon.com/images/I/71SVw8xvHiL.SL1500.jpg",
  image3: "https://m.media-amazon.com/images/I/716AWBdP8eL.SL1500.jpg",
  category: "food",
  pet: "aquaticpets",
  rating: 4.7,
  reviewCount: 4,
  featured: true,
  stock: 60,
  tags: ["fish food", "red parrot", "high protein", "color enhancement"]
},
{
  id: "30",
  name: "PRIONS BIOTECH Aqua Safe PR (1L)",
  slug: "prions-biotech-aqua-safe-pr-1l",
  description: "Eco-friendly nanotech disinfectant for shrimp & aquarium fish 💧 Controls bacteria, fungi, protozoa & viruses. Non‑toxic, iodine‑based formula—safe for live stock and water.",
  price: 1699,
  originalPrice:2000,
  image: "https://m.media-amazon.com/images/I/617dndFl9bL.SL1500.jpg",
  image1: "https://m.media-amazon.com/images/I/71BCNsdyl0L.SL1000.jpg",
  image2: "https://m.media-amazon.com/images/I/61yA23IhKjL.SL1000.jpg",
  image3: "https://m.media-amazon.com/images/I/61q6OmIh4EL.SL1000.jpg",
  category: "supplements",
  pet: "aquaticpets",
  rating: 4.5,
  reviewCount: 10,
  featured: false,
  stock: 30,
  tags: ["disinfectant", "water treatment", "shrimp", "nano"],
},
{
  id: "31",
  name: "BACTONIL-FW Freshwater Anti-Bacterial Solution (120 ml)",
  slug: "bactonil-fw-freshwater-antibacterial-120ml",
  description: "Broad-spectrum antibacterial remedy for flowerhorn, arowana & discus. Treats fin rot, mouth fungus, ulcers, cloudy eye, pop‑eye & skin discoloration. Suitable for quarantine/hospital tanks.",
  price: 178,
  image: "https://m.media-amazon.com/images/I/71eAmcyIXRL.SL1500.jpg",
  image1: "https://m.media-amazon.com/images/I/717QIhkBAuL.SL1500.jpg",
  image2: "https://m.media-amazon.com/images/I/712b+FFtW8L.SL1500.jpg",
  image3: "https://m.media-amazon.com/images/I/71iJGsW3iCL.SL1500.jpg",
  category: "supplements",
  pet: "aquaticpets",
  rating: 4.0,
  reviewCount: 356,
  featured: false,
  stock: 40,
  tags: ["fish medication", "antibacterial", "quarantine", "fin rot treatment"]
},
{
  id: "32",
  name: "RUKDA Natural Black Rock - 3kg Decorative Stones",
  slug: "rukda-natural-black-rock-3kg",
  description: "Premium natural black decorative stones (7–12 cm pieces) ideal for aquariums, terrariums, gardens and home decor. Adds contrast and surface area for beneficial bacteria growth.",
  price: 650,
  image: "https://m.media-amazon.com/images/I/71FNTBoNpZL.SL1500.jpg",
  image1: "https://m.media-amazon.com/images/I/81HOeonb3WL.SL1500.jpg",
  image2: "https://m.media-amazon.com/images/I/81caTbvjj4L.SL1500.jpg",
  image3: "https://m.media-amazon.com/images/I/8104cgCh59L.SL1500.jpg",
  category: "toys",
  pet: "aquaticpets",
  rating: 4.5,
  reviewCount: 12,
  featured: false,
  stock: 20,
  tags: ["black rock", "aquascape", "decorative stone", "aquarium accessory"]
},
{
  id: "33",
  name: "SANSEFERO Premier Plants Aquarium Decor - Broken Bus Hideaway",
  slug: "sansefero-broken-bus-aquarium-decor",
  description: "Non-toxic resin decorative “broken bus” hideaway ornament for small & medium fish, ideal as a fun thematic cave—smooth, fish-safe edges.",
  price: 900,
  image: "https://m.media-amazon.com/images/I/71ucUmVBoNL.SL1080.jpg",
  image1: "https://m.media-amazon.com/images/I/6158QoMaYQL.SL1080.jpg",
  image2: "https://m.media-amazon.com/images/I/71+LLnVcFuL.SL1080.jpg",
  image3: "https://m.media-amazon.com/images/I/61QEjWpV0zL.SL1080.jpg",
  category: "toys",
  pet: "aquaticpets",
  rating: 5.0,
  reviewCount: 1,
  featured: false,
  stock: 30,
  tags: ["aquarium decor", "fish hideaway", "resin ornament", "broken bus"]
},
{
  id: "34",
  name: "Rizopets Turtle Tank Kit (Medium, 44 × 22 × 25 cm)",
  slug: "rizopets-turtle-tank-kit-medium",
  description: "Complete turtle habitat with filter, water pump, wheels, and natural‑flow design—perfect for small turtles, horned frogs, hermit crabs. Easy to move and maintain.",
  price: 1,
  originalPrice:1789,
  image: "https://m.media-amazon.com/images/I/51cbApdb3FL.jpg",
  image1: "https://m.media-amazon.com/images/I/414gNrxQOaL.jpg",
  image2: "https://m.media-amazon.com/images/I/51SK5xUXdqL.jpg",
  image3: "https://m.media-amazon.com/images/I/41nBojjzUTL.jpg",
  category: "grooming supplies",
  pet: "aquaticpets",
  rating: 3.5,
  reviewCount: 80,
  featured: false,
  stock: 25,
  tags: ["turtle tank", "filter kit", "portable", "habitat kit"]
}








]